apiVersion: v1
kind: Service
metadata:
  name: airflow-service
  namespace: default
  labels:
    app: airflow
spec:
  type: NodePort
  selector:
    app: airflow
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30009  # Puedes dejarlo en autoasignación si prefieres
