apiVersion: v1
kind: Secret
metadata:
  name: airflow-secret
  namespace: default
type: Opaque
data:
  AIRFLOW_USERNAME: YWRtaW4=   # admin (Base64 encoded)
  AIRFLOW_PASSWORD: YWRtaW4=   # admin (Base64 encoded)
  AIRFLOW_FERNET_KEY: Z3FxMFcyWk5aVVhKTTVHRTdlS0w0N0lCWUdmT1FSa0pma29qZGtjbXZzTT0=  # Codifica en Base64 antes de ponerlo aquí
