apiVersion: v1
kind: Secret
metadata:
  name: airflow-secret
  namespace: default
type: Opaque
data:
  AIRFLOW_USERNAME: YWRtaW4=   # admin (Base64 encoded)
  AIRFLOW_PASSWORD: YWRtaW4=   # admin (Base64 encoded)
