apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-deployment
  namespace: default
  labels:
    app: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow
  template:
    metadata:
      labels:
        app: airflow
    spec:
      containers:
      containers:
        - name: airflow
          command: ["/bin/bash", "-c"]
          args:
            - airflow db init &&
              airflow webserver
          image: apache/airflow:2.6.3
          env:
            - name: AIRFLOW__WEBSERVER__RBAC
              value: "True"
            - name: AIRFLOW__CORE__EXECUTOR
              value: "SequentialExecutor"
            - name: AIRFLOW__CORE__FERNET_KEY
              valueFrom:
                secretKeyRef:
                  name: airflow-secret
                  key: AIRFLOW_FERNET_KEY
            - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
              value: "postgresql+psycopg2://postgres:securepass@postgres-service:5432/airflow"
            - name: AIRFLOW__WEBSERVER__AUTH_BACKEND
              value: "airflow.contrib.auth.backends.password_auth"
            - name: AIRFLOW_USERNAME
              valueFrom:
                secretKeyRef:
                  name: airflow-secret
                  key: AIRFLOW_USERNAME
            - name: AIRFLOW_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: airflow-secret
                  key: AIRFLOW_PASSWORD

          ports:
            - containerPort: 8080
          volumeMounts:
            - name: airflow-storage
              mountPath: /opt/airflow/dags
      volumes:
        - name: airflow-storage
          persistentVolumeClaim:
            claimName: airflow-pvc
