apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: default
  labels:
    app: mongodb
type: Opaque
data:
  MONGO_ROOT_USERNAME: bW9uZ29hZG1pbg==  # "mongoadmin" encoded in base64
  MONGO_ROOT_PASSWORD: c2VjdXJlcGFzcw==  # "securepass" encoded in base64