apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: default
  labels:
    app: mysql
stringData:
  MYSQL_ROOT_PASSWORD: pass
  MYSQL_DATABASE: softcartdb
  MYSQL_USER: softcartuser
  MYSQL_PASSWORD: pass
