apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin-deployment
  labels:
    app: pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
        - name: pgadmin
          image: dpage/pgadmin4
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              valueFrom:
                secretKeyRef:
                  name: pgadmin-secret
                  key: PGADMIN_DEFAULT_EMAIL
            - name: PGADMIN_DEFAULT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgadmin-secret
                  key: PGADMIN_DEFAULT_PASSWORD
            - name: PGADMIN_ENABLE_FILE_BROWSER
              value: "True"
            - name: PGADMIN_CONFIG_SERVER_MODE
              value: "False"
            - name: PGADMIN_DEFAULT_STORAGE_LOCATION
              value: "/var/lib/pgadmin/storage"
          ports:
            - containerPort: 80
          volumeMounts:
            - name: pgadmin-config
              mountPath: /pgadmin4/servers.json
              subPath: servers.json
            - name: pgpass-file
              mountPath: /pgpass
              subPath: pgpass
              readOnly: true
            - name: pgadmin-data
              mountPath: /var/lib/pgadmin/storage


      volumes:
        - name: pgadmin-config
          configMap:
            name: pgadmin-config
        - name: pgpass-file
          secret:
            secretName: pgpass-secret
        - name: pgadmin-data
          persistentVolumeClaim:
            claimName: pgadmin-pvc


