apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: default
  labels:
    app: postgres
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=  # "postgres" encoded in base64
  POSTGRES_PASSWORD: c2VjdXJlcGFzcw==  # "securepass" encoded in base64
  POSTGRES_DB: ZGF0YWhvdXNl  # "datawarehouse" encoded in base64